# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f92db250fde848590f3dbeb3b6a3287755a3d9ce644aa5ae946c74a6c5370c9462d157378dde2cd61cbcbf5b5185eb87a4d254cc3f202b4146eaae93787d6f

test:
  secret_key_base: 929cceede4a7925777d857c04d57d6b1f53bd7e758392a91f29b6e25e8e3ab85bd2d86f810fafd9e23dc740599c1e2b3bea212b9364676477736075eb2f5e269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
